language: python
python:
    - "2.7"

#command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r package/requirements.txt --extra-index-url https://testpypi.python.org/simple --extra-index-url https://testpypi.python.org/pypi
  - pip install cloudshell-shell-core --extra-index-url https://pypi.python.org/simple
  - pip install -r test_requirements.txt
  - pip install coveralls

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls
    
#notifications:
# webhools: https://qualisystems.getbadges.io/api/app/webhook/{will be added later}
